basic:
    name: easypersonalloans.com.au
    environments:
        production: 'https://easypersonalloans.com.au'
        staging: 'https://staging.easypersonalloans.com.au'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1920
    pages:
        - /
    monitoring:
        days: [Mon]
        type: weekly
        schedule_time: '06:30 AM'
        schedule_time_zone: Australia/Brisbane
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ".trusted-home-marquee__group\n.ti-widget-container\n#pr-reviews-carousel-widget"
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
